'use strict';
const STATES={rough:['correction','proofread'],correction:['proofread'],proofread:['correction','certification_pending'],certification_pending:['correction','certified'],certified:['superseded'],superseded:[]};
function assert(ok,message){if(!ok){const e=new Error(message);e.status=422;throw e;}}
function context(user,tenantId,roles){assert(user&&user.id,'authenticated actor required');assert(tenantId,'x-tenant-id is required');if(user.tenantId||user.tenant_id)assert((user.tenantId||user.tenant_id)===tenantId,'tenant mismatch');const role=user.role||'viewer';assert(roles.includes(role),'role not authorized');return{tenantId,actorId:String(user.id),role};}
function validateMedia(input){assert(/^https:\/\/|^s3:\/\/|^gs:\/\//.test(input.objectUri||''),'media must use HTTPS or object storage');assert(/^[a-f0-9]{64}$/i.test(input.sha256||''),'sha256 is invalid');assert(Number.isSafeInteger(input.durationMs)&&input.durationMs>0,'durationMs must be positive');assert(String(input.authorizationReference||'').trim().length>=3,'recording authorization is required');return input;}
function validateVersion(input){assert(/^https:\/\/|^s3:\/\/|^gs:\/\//.test(input.objectUri||''),'transcript objectUri is invalid');assert(/^[a-f0-9]{64}$/i.test(input.sha256||''),'sha256 is invalid');for(const key of ['wordErrorRate','diarizationErrorRate','timestampCoverage']){if(input[key]!==undefined){const n=Number(input[key]);assert(n>=0&&n<=1,`${key} must be between 0 and 1`);}}return input;}
function transition(from,to){assert(STATES[from]&&STATES[from].includes(to),`invalid transition ${from} -> ${to}`);return to;}
function canCertify({actor,version,pendingCorrections,credentialReference}){assert(actor&&actor.role==='reporter','only a court reporter may certify');assert(version&&version.state==='certification_pending','version is not ready for certification');assert(version.redaction_status!=='unreviewed','redaction review is required');assert(pendingCorrections===0,'pending corrections must be resolved');assert(String(credentialReference||'').trim().length>=3,'reporter credential reference is required');return true;}
function canDeliver(version,certification,matterAccess){assert(version&&version.state==='certified','only certified versions may be delivered');assert(certification,'certification record is required');assert(matterAccess===true,'recipient matter authorization is required');return true;}
function validateCorrection(input){assert(String(input.pageLineReference||'').trim(),'page/line reference is required');assert(input.originalText!==input.correctedText,'correction must change text');assert(String(input.reason||'').trim().length>=3,'correction reason is required');return input;}
module.exports={STATES,context,validateMedia,validateVersion,validateCorrection,transition,canCertify,canDeliver};
